name: Build Utest

on: [push, pull_request]

jobs:
  job_1:
    name: restart
    runs-on: ubuntu-latest
    #runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Try squash build
      run: |
        printf '{\n    "experimental": true\n}' | sudo tee /etc/docker/daemon.json >/dev/null
        sudo cat /etc/docker/daemon.json
        sudo systemctl restart docker
        sleep 10
        
    - name: Build docker image
      run: cd tests && ./ci.sh -b -c restart

    - name: Clean up intermediaries
      run: |
        df -h
        docker image ls
        docker rmi $(docker image ls | grep -E -m1 '<none>' | awk '{ print $3 }')
        docker rmi $(docker image ls | awk '/fv3-input-data/ { print $3 }')
        docker rmi $(docker image ls | awk '/ci-test-base/ { print $3 }')
        docker image ls
        df -h

    - name: Run docker image
      run: cd tests && ./ci.sh -r

    - name: Some further tests
      if: ${{ always() }}
      run: |
        echo $(pwd)
        ls -a /home/runner/work/ufs-weather-model
        ls -a /home/runner/work/ufs-weather-model/ufs-weather-model
        df -h

    - name: Upload memory usage
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: memory-statistics
        path: tests/memory-stat.txt
