name: Build Utest

on: [push, pull_request]

jobs:
  job_1:
    name: std 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Try squash build
      run: |
        sudo ls /etc/docker
        sudo cat /etc/docker/daemon.json
        printf '{\n    "experimental": true\n}' >daemon.json
        sudo mv daemon.json /etc/docker
        sudo cat /etc/docker/daemon.json
        sudo systemctl restart docker
        sleep 10
        
    - name: Build docker image
      run: cd tests && ./ci.sh -b -c restart

    - name: Clean up intermediaries
      run: |
        df -h
        docker image ls
        docker rmi $(docker image ls | grep -E -m1 '<none>' | awk '{ print $3 }')
        docker rmi $(docker image ls | awk '/develop/ { print $3 }')
        docker rmi $(docker image ls | awk '/utest/ { print $3 }')
        docker image ls
        df -h
        #docker images; docker ps -a -q; docker rm $(docker ps -a -q); imageID=$(docker images | grep -m1 '<none>' | awk '{print $3}'); docker rmi $imageID
        #run: docker rmi minsukjinoaa/develop-20200202-fv3-input minsukjinoaa/utest-base; docker images

    #- name: Run docker image
    #  run: cd tests && ./ci.sh -r
