name: Build Utest

on: [push, pull_request]

jobs:
  job_1:
    name: std 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Build docker image
      run: cd tests && ./ci.sh -b -c restart

    - name: Clean up intermediaries
      run: |
        docker image ls
        docker image ls | awk '/develop/ { print $3 }'
        docker rmi $(docker image ls | awk '/develop/ { print $3 }')
        docker image ls
        #docker images; docker ps -a -q; docker rm $(docker ps -a -q); imageID=$(docker images | grep -m1 '<none>' | awk '{print $3}'); docker rmi $imageID
        #run: docker rmi minsukjinoaa/develop-20200202-fv3-input minsukjinoaa/utest-base; docker images

    - name: Run docker image
      run: cd tests && ./ci.sh -r
